name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Show Go environment
        run: |
          go version
          go env

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run tests (race, shuffled)
        run: |
          mkdir -p artifacts
          gotestsum --junitfile artifacts/junit.xml --format=short-verbose -- \
            -race -coverprofile=artifacts/coverage.out -covermode=atomic -shuffle=on -count=1 ./...
        env:
          PATH: ${{ env.PATH }}:$(go env GOPATH)/bin

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: artifacts/
          if-no-files-found: warn

      - name: Publish JUnit Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: artifacts/junit.xml
          detailed_summary: true
          include_passed: true